BEGIN;
DO $relecture$
BEGIN
UPDATE public.pedagogical_content SET question = 'Comment observer le vivant sans déranger ?', objectif = 'Retenir qu’il y a dérangement dès qu’il y a un changement de comportement.', tip = 'Rester à distance, ne pas faire de bruit, utiliser des jumelles.' WHERE id = '62' AND ((question IS NOT DISTINCT FROM 'Comment savoir si on dérange un animal ?' AND objectif IS NOT DISTINCT FROM 'Retenir qu''il y a dérangement dès qu''il y a un changement de comportement.' AND tip IS NOT DISTINCT FROM 'Jumelles et silence. Faites observer un oiseau au groupe : s''il relève la tête ou s''arrête de se nourrir, on a déjà fait un pas de trop — on recule.') OR (question IS NOT DISTINCT FROM 'Comment observer le vivant sans déranger ?' AND objectif IS NOT DISTINCT FROM 'Retenir qu’il y a dérangement dès qu’il y a un changement de comportement.' AND tip IS NOT DISTINCT FROM 'Rester à distance, ne pas faire de bruit, utiliser des jumelles.'));
IF NOT FOUND THEN RAISE EXCEPTION 'Card 62 differs from the reviewed version'; END IF;
UPDATE public.pedagogical_content SET objectif = 'Comprendre qu’au fil des saisons, le vivant est différent et choisit le site en fonction de ses besoins : hivernage, reproduction, halte migratoire…', tip = 'Il y a des moments clés à chaque saison pour chaque espèce. Il est important de les repérer pour savoir qui est là, à quel moment et pourquoi.' WHERE id = '65' AND ((objectif IS NOT DISTINCT FROM 'Comprendre la multifonctionnalité des habitats et l''importance de les préserver.' AND tip IS NOT DISTINCT FROM 'Demandez au groupe : qui habite la plage cette semaine ? Cherchez un indice du moment (nid, jeunes, groupe en halte) et expliquez pourquoi cette espèce a choisi ce site à cette saison.') OR (objectif IS NOT DISTINCT FROM 'Comprendre qu’au fil des saisons, le vivant est différent et choisit le site en fonction de ses besoins : hivernage, reproduction, halte migratoire…' AND tip IS NOT DISTINCT FROM 'Il y a des moments clés à chaque saison pour chaque espèce. Il est important de les repérer pour savoir qui est là, à quel moment et pourquoi.'));
IF NOT FOUND THEN RAISE EXCEPTION 'Card 65 differs from the reviewed version'; END IF;
UPDATE public.pedagogical_content SET question = 'Comment prendre en compte les rythmes naturels ?', objectif = 'Comprendre que les activités humaines sont soumises à différents rythmes : le rythme quotidien des marées, le rythme mensuel des cycles de la Lune, le rythme annuel des saisons…', tip = 'La nature aura toujours le dernier mot : à charge pour l’homme d’ajuster ses activités pour être en sécurité et en harmonie avec le lieu. L’adaptation à tous ces rythmes passe par la connaissance.', explication = 'Les activités humaines s’ajustent à plusieurs rythmes naturels : les marées au quotidien, les cycles de la Lune au fil du mois et les saisons au cours de l’année. Ces rythmes changent les conditions de pratique et la présence du vivant. Les connaître aide à choisir un moment et un lieu adaptés.

Sur un site soumis aux marées, un accès peut demander une certaine hauteur d’eau ou un courant adapté. D’un jour à l’autre, les horaires de pleine et de basse mer se décalent, mais les hauteurs changent aussi avec des marées qui gagnent ou perdent de l’ampleur. On ne peut donc pas toujours reprendre le créneau de la veille en le décalant simplement : la plage horaire utilisable peut s’allonger, se raccourcir ou disparaître.', a_retenir = 'Tenir compte des marées, des cycles de la Lune et des saisons pour adapter ses activités au lieu et au moment.' WHERE id = '68' AND ((question IS NOT DISTINCT FROM 'Pourquoi on ne part pas à la même heure chaque jour ?' AND objectif IS NOT DISTINCT FROM 'Comprendre que les activités nautiques suivent les rythmes de la nature : la marée chaque jour, les coefficients sur deux semaines, les saisons sur l’année.' AND tip IS NOT DISTINCT FROM 'Choisissez un exemple réel du club ; tous les horaires de séance ne sont pas imposés par la marée.' AND explication IS NOT DISTINCT FROM 'Sur un site soumis aux marées, un accès peut demander une certaine hauteur d’eau ou un courant adapté. D’un jour à l’autre, les horaires de pleine et de basse mer se décalent, mais les hauteurs changent aussi avec des marées qui gagnent ou perdent de l’ampleur. On ne peut donc pas toujours reprendre le créneau de la veille en le décalant simplement : la plage horaire utilisable peut s’allonger, se raccourcir ou disparaître.' AND a_retenir IS NOT DISTINCT FROM 'Pour retrouver un créneau adapté, on compare les horaires et les hauteurs d’eau de chaque journée.') OR (question IS NOT DISTINCT FROM 'Comment prendre en compte les rythmes naturels ?' AND objectif IS NOT DISTINCT FROM 'Comprendre que les activités humaines sont soumises à différents rythmes : le rythme quotidien des marées, le rythme mensuel des cycles de la Lune, le rythme annuel des saisons…' AND tip IS NOT DISTINCT FROM 'La nature aura toujours le dernier mot : à charge pour l’homme d’ajuster ses activités pour être en sécurité et en harmonie avec le lieu. L’adaptation à tous ces rythmes passe par la connaissance.' AND explication IS NOT DISTINCT FROM 'Les activités humaines s’ajustent à plusieurs rythmes naturels : les marées au quotidien, les cycles de la Lune au fil du mois et les saisons au cours de l’année. Ces rythmes changent les conditions de pratique et la présence du vivant. Les connaître aide à choisir un moment et un lieu adaptés.

Sur un site soumis aux marées, un accès peut demander une certaine hauteur d’eau ou un courant adapté. D’un jour à l’autre, les horaires de pleine et de basse mer se décalent, mais les hauteurs changent aussi avec des marées qui gagnent ou perdent de l’ampleur. On ne peut donc pas toujours reprendre le créneau de la veille en le décalant simplement : la plage horaire utilisable peut s’allonger, se raccourcir ou disparaître.' AND a_retenir IS NOT DISTINCT FROM 'Tenir compte des marées, des cycles de la Lune et des saisons pour adapter ses activités au lieu et au moment.'));
IF NOT FOUND THEN RAISE EXCEPTION 'Card 68 differs from the reviewed version'; END IF;
END;
$relecture$;
COMMIT;
