-- Les actions de terrain, rattachées à la fiche pédagogique.
--
-- Elles vivaient dans un fichier local indexé par identifiant de fiche. C'était pratique
-- pour rédiger vite, mais bancal en modélisation : une action est du contenu pédagogique
-- au même titre que `accroche`, `a_observer`, `a_retenir` ou `erreur_frequente`, tous
-- portés par cette table. Rien ne justifiait de la tenir à part — et cette séparation
-- interdisait toute correction depuis l'administration.
--
-- Le format retenu est JSONB plutôt qu'une table liée : une action est un triplet
-- indissociable (id, label, consigne) dont l'ordre compte, jamais requêté indépendamment
-- de sa fiche. Une table séparée imposerait une jointure sur chaque lecture de fiche sans
-- rien apporter.
--
--     [{"id": "f200_ou_pousse_vent",
--       "label": "De quel côté elles sont",
--       "consigne": "Faites repérer le sens du vent…"}]
--
-- Les identifiants d'action sont stables : `stage_preparations.actions` les référence
-- pour mémoriser ce que le moniteur a retenu. Les renommer orpheline ces choix.
ALTER TABLE pedagogical_content ADD COLUMN IF NOT EXISTS actions JSONB;

COMMENT ON COLUMN pedagogical_content.actions IS
  'Actions de terrain proposées pour cette fiche : [{id, label, consigne}]. Les id sont référencés par stage_preparations.actions.';

-- Contenu des 25 fiches déjà rédigées (marées et vie dans l'eau, groupes complets).
UPDATE pedagogical_content SET actions = '[{"id":"f1_pourquoi_deux","label":"Pourquoi deux fois ?","consigne":"Laissez-les dire que la Lune attire l’eau. Puis : « si elle tire d’un côté, pourquoi la mer monte aussi de l’autre ? »"},{"id":"f1_terre_tourne","label":"La Terre tourne, pas l’eau","consigne":"Un stagiaire fait la Lune, un autre la Terre qui tourne sur elle-même. Deux autres tiennent les bosses d’eau, fixes. On voit qui traverse quoi."},{"id":"f1_vent_ou_lune","label":"Le vent ou la Lune ?","consigne":"Faites voter à main levée. Beaucoup diront le vent. Le vent fait les vagues, pas la marée."}]'::jsonb WHERE id = '1';
UPDATE pedagogical_content SET actions = '[{"id":"f2_lire_annuaire","label":"Lisez-moi l’heure de ce soir","consigne":"Passez l’annuaire ou le téléphone à un stagiaire et faites-lui trouver la marée haute du soir. Puis celle de dimanche prochain."},{"id":"f2_dans_dix_ans","label":"Et dans dix ans ?","consigne":"Demandez si on peut connaître la marée du 14 juillet 2040. Oui — et à la minute près."}]'::jsonb WHERE id = '2';
UPDATE pedagogical_content SET actions = '[{"id":"f3_deux_ports","label":"Deux ports, deux heures","consigne":"Comparez l’horaire d’ici avec celui d’un port voisin sur l’annuaire. Faites chercher pourquoi l’écart existe."},{"id":"f3_onde_carte","label":"Le chemin de la vague","consigne":"Sur une carte, faites tracer du doigt la route de l’onde : le cap à contourner, la baie à remplir."}]'::jsonb WHERE id = '3';
UPDATE pedagogical_content SET actions = '[{"id":"f4_montrez_estran","label":"Montrez-moi l’estran","consigne":"Faites délimiter à deux, bras écartés, la bande qui se découvre. Le mot s’installe en le montrant."},{"id":"f4_six_heures_sec","label":"Six heures à sec","consigne":"Faites lister ce que subit un animal ici en une journée : noyé, à sec, chaud, froid, salé. Puis : « et toi, tu tiendrais ? »"}]'::jsonb WHERE id = '4';
UPDATE pedagogical_content SET actions = '[{"id":"f6_meteo_change_heure","label":"La météo change-t-elle l’heure ?","consigne":"Faites voter. Le vent change la hauteur de l’eau, jamais l’horaire — c’est un calcul astronomique."}]'::jsonb WHERE id = '6';
UPDATE pedagogical_content SET actions = '[{"id":"f8_deux_marques","label":"Deux marques, une heure d’écart","consigne":"Marquez le bord de l’eau en arrivant, remarquez une heure plus tard, puis encore une heure. Les écarts ne sont pas égaux."},{"id":"f8_quand_ca_monte_vite","label":"À quel moment ça monte le plus vite ?","consigne":"Faites parier : début, milieu ou fin. La plupart disent la fin. C’est au milieu — et c’est là qu’on se fait surprendre."}]'::jsonb WHERE id = '8';
UPDATE pedagogical_content SET actions = '[{"id":"f9_objet_derive","label":"L’objet qui file","consigne":"Lâchez un objet flottant à mi-marée, recommencez près de l’étale. La différence de vitesse se voit sans explication."},{"id":"f9_courant_maxi","label":"Le courant le plus fort, c’est quand ?","consigne":"Faites voter entre marée haute, marée basse et mi-marée. La majorité se trompe : c’est à mi-marée."}]'::jsonb WHERE id = '9';
UPDATE pedagogical_content SET actions = '[{"id":"f10_on_en_est_ou","label":"On en est où, là ?","consigne":"Demandez de nommer le moment présent : flot, jusant ou étale. Reposez la question deux heures plus tard."},{"id":"f10_mot_du_jour","label":"Le mot qui manque","consigne":"Donnez deux mots sur trois — flot et jusant — et faites-leur trouver celui du moment où rien ne bouge."}]'::jsonb WHERE id = '10';
UPDATE pedagogical_content SET actions = '[{"id":"f11_qui_travaille_maintenant","label":"Qui travaille à cette heure-ci","consigne":"Faites lister ce qui n’est possible que maintenant, à cette marée : pêcheurs à pied, oiseaux qui fouillent, sortie du port."},{"id":"f11_meme_endroit_six_heures","label":"Ici dans six heures","consigne":"Faites décrire l’endroit où vous êtes tel qu’il sera à la marée opposée. Qui y sera, qui n’y sera plus."}]'::jsonb WHERE id = '11';
UPDATE pedagogical_content SET actions = '[{"id":"f12_jusqu_ou_aujourdhui","label":"Jusqu’où on peut aller aujourd’hui","consigne":"Montrez la limite découverte du jour, puis celle d’une grande marée. Faites mesurer l’écart en nombre de pas."},{"id":"f12_rendez_vous_annuel","label":"Le rendez-vous qu’elles attendent","consigne":"Demandez pourquoi une espèce pondrait précisément un jour de grande marée. Réponse : le courant emporte les larves loin."}]'::jsonb WHERE id = '12';
UPDATE pedagogical_content SET actions = '[{"id":"f13_repere_cinq_minutes","label":"Le repère et cinq minutes","consigne":"Chacun choisit un caillou au bord de l’eau. On revient cinq minutes plus tard voir s’il est couvert."},{"id":"f13_regarde_la_monter","label":"Essayez de la voir monter","consigne":"Faites-les fixer l’eau une minute pour voir le niveau bouger. Impossible — c’est le repère qui révèle, pas l’œil."}]'::jsonb WHERE id = '13';
UPDATE pedagogical_content SET actions = '[{"id":"f14_ou_poser_affaires","label":"Où tu poses tes affaires ?","consigne":"Chacun montre où il poserait son sac. Puis montrez la ligne d’algues et faites recommencer."},{"id":"f14_saleté_ou_repere","label":"Saleté ou repère ?","consigne":"Demandez ce qu’est cette ligne de débris. Beaucoup diront « des déchets ». C’est le niveau exact de la dernière marée haute."}]'::jsonb WHERE id = '14';
UPDATE pedagogical_content SET actions = '[{"id":"f15_coefficient_monte","label":"Et si le coefficient monte ?","consigne":"Montrez la laisse d’hier, donnez le coefficient du jour. Faites-leur dire si la ligne d’hier suffit — non, si le coefficient grimpe."},{"id":"f15_marge_en_pas","label":"La marge en nombre de pas","consigne":"Faites décider collectivement à combien de pas au-dessus de la laisse on installe le matériel. Ils défendent leur chiffre."}]'::jsonb WHERE id = '15';
UPDATE pedagogical_content SET actions = '[{"id":"f16_ca_a_l_air_vide","label":"Ça a l’air vide","consigne":"Faites regarder un carré de sable qui semble désert, puis gratter doucement. Ce qui sort change le regard sur le pas suivant."},{"id":"f16_ou_on_marche","label":"Où on met les pieds","consigne":"Avant de traverser l’estran, faites choisir collectivement le trajet qui abîme le moins. Ils justifient leur choix."}]'::jsonb WHERE id = '16';
UPDATE pedagogical_content SET actions = '[{"id":"f91_cinquante_minutes","label":"Le décalage à trouver","consigne":"Faites lire l’heure de marée d’aujourd’hui et de demain, puis calculer l’écart. Ils trouvent cinquante minutes tout seuls."},{"id":"f91_lune_en_retard","label":"La Lune arrive en retard","consigne":"Un stagiaire tourne sur lui-même (la Terre), un autre marche lentement autour (la Lune). Il faut plus d’un tour pour la retrouver en face."}]'::jsonb WHERE id = '91';
UPDATE pedagogical_content SET actions = '[{"id":"f5_chrono_etale","label":"Le chrono de l’étale","consigne":"Faites déclencher un chrono quand ils pensent que l’eau ne bouge plus, et l’arrêter quand elle repart. Comparez les durées annoncées."},{"id":"f5_repere_cale","label":"Le repère sur la cale","consigne":"Marquez le niveau de l’eau sur la cale, revenez dix minutes plus tard. Pendant l’étale, la marque ne bouge presque pas."}]'::jsonb WHERE id = '5';
UPDATE pedagogical_content SET actions = '[{"id":"f7_nombre_sans_unite","label":"Le nombre sans unité","consigne":"Demandez ce que « 95 » représente en mètres. Personne ne sait — c’est normal, ce n’est pas une hauteur."},{"id":"f7_deux_journees","label":"Deux journées comparées","consigne":"Montrez le marnage d’un jour à coefficient 40 et d’un jour à 100. Faites dire ce que ça change pour la séance."}]'::jsonb WHERE id = '7';
UPDATE pedagogical_content SET actions = '[{"id":"f58_probleme_solution","label":"Le problème avant la solution","consigne":"Annoncez la contrainte — six heures à sec, puis les vagues — et faites-leur inventer une solution avant de montrer celle de l’animal."},{"id":"f58_une_bete_un_truc","label":"Une bête, un truc","consigne":"Chacun choisit un animal sur l’estran et doit nommer son astuce : carapace, ventouse, coquille qui se ferme, souplesse."},{"id":"f58_arracher_patelle","label":"Essaie de la décoller","consigne":"Laissez-les tenter de décoller une patelle à la main. L’échec explique la ventouse mieux qu’un discours."}]'::jsonb WHERE id = '58';
UPDATE pedagogical_content SET actions = '[{"id":"f59_remonter_chaine","label":"La chaîne à l’envers","consigne":"Partez d’un poisson qu’ils connaissent et remontez : qui le mange, que mange-t-il. Continuez jusqu’à ce qu’ils sèchent — on y arrive vite."},{"id":"f59_maillon_retire","label":"On enlève un maillon","consigne":"Une fois la chaîne posée, supprimez un maillon du milieu et demandez qui, au-dessus, a encore de quoi manger."},{"id":"f59_invisible_verre","label":"Le verre d’eau de mer","consigne":"Montrez un verre d’eau de mer : elle paraît vide. Annoncez ce qu’il contient, puis demandez qui en dépend."}]'::jsonb WHERE id = '59';
UPDATE pedagogical_content SET actions = '[{"id":"f60_meme_endroit_mars","label":"Ici, il y a trois mois","consigne":"Demandez ce qu’on aurait vu au même endroit en mars. Puis ce qu’on y verra en décembre."},{"id":"f60_calendrier_espece","label":"Le calendrier de l’espèce","consigne":"Prenez une espèce vue aujourd’hui et faites reconstituer son année : où elle naît, où elle mange, où elle passe l’hiver."}]'::jsonb WHERE id = '60';
UPDATE pedagogical_content SET actions = '[{"id":"f88_combien_especes","label":"Le pari sur le nombre","consigne":"Faites-leur parier combien d’espèces de mammifères marins ont été vues en Normandie. Ils diront deux ou trois — il y en a vingt-quatre."},{"id":"f88_dix_minutes_large","label":"Dix minutes vers le large","consigne":"Fixez un secteur et dix minutes de guet. On cherche une tête ronde, un souffle, un aileron. Même bredouille, on a appris à regarder."},{"id":"f88_trois_reguliers","label":"Les trois du coin","consigne":"Faites retenir les trois espèces visibles toute l’année : phoque veau-marin, phoque gris, marsouin. Reposez la question demain."}]'::jsonb WHERE id = '88';
UPDATE pedagogical_content SET actions = '[{"id":"f128_pourquoi_eux","label":"Pourquoi surveiller ceux-là ?","consigne":"Demandez pourquoi on suit les phoques plutôt que les crevettes. La réponse : ils vivent vieux et mangent tout le reste."},{"id":"f128_ce_qui_remonte","label":"Ce qui remonte jusqu’en haut","consigne":"Reprenez la chaîne alimentaire et faites suivre un polluant du plancton jusqu’au phoque. Il se concentre à chaque étage."}]'::jsonb WHERE id = '128';
UPDATE pedagogical_content SET actions = '[{"id":"f200_ou_pousse_vent","label":"De quel côté elles sont","consigne":"Faites repérer le sens du vent, puis chercher où les méduses s’accumulent. C’est le même côté — la démonstration se fait toute seule."},{"id":"f200_elles_attaquent","label":"Elles nous attaquent ?","consigne":"Laissez-les dire que les méduses viennent vers la plage. Puis demandez avec quoi elles nageraient : ni nageoires, ni queue."},{"id":"f200_pari_demain","label":"Le pari sur demain","consigne":"Regardez la prévision de vent et faites parier s’il y aura des méduses demain. Vérifiez à la séance suivante."}]'::jsonb WHERE id = '200';
UPDATE pedagogical_content SET actions = '[{"id":"f201_quatre_trefles","label":"Cherchez les quatre trèfles","consigne":"Faites chercher les quatre anneaux en trèfle au centre de l’ombrelle : c’est l’aurélie, la plus courante, et elle ne traverse pas notre peau."},{"id":"f201_dessin_avant_nom","label":"Le dessin avant le nom","consigne":"Faites décrire les motifs avant de donner le nom : anneaux en trèfle, traits bruns en rayons, gros dôme bleuté."},{"id":"f201_toutes_pareil","label":"Elles piquent toutes pareil ?","consigne":"Faites voter à main levée. La majorité dira oui — c’est faux, et c’est ce qui rend l’identification utile."}]'::jsonb WHERE id = '201';
UPDATE pedagogical_content SET actions = '[{"id":"f202_morte_donc_inoffensive","label":"Morte, donc inoffensive ?","consigne":"Posez la question devant une méduse échouée. Presque tous diront oui. Elle pique encore des semaines, même en morceaux."},{"id":"f202_qui_vient_manger","label":"Qui vient la manger","consigne":"Faites chercher les traces autour : becs d’oiseaux, morceaux arrachés. Une méduse échouée n’est pas un déchet."},{"id":"f202_fragment_invisible","label":"Le bout qu’on ne voit pas","consigne":"Faites remarquer qu’un tentacule cassé reste dans le sable. Regarder où on met les mains vaut mieux que ramasser."}]'::jsonb WHERE id = '202';