-- Actions de terrain : vent.
--
-- Générées par scripts/importer-actions.mjs. Les actions vivent dans la fiche
-- (`pedagogical_content.actions`), au même titre que l'accroche ou l'idée à retenir.
-- Leurs identifiants sont référencés par `stage_preparations.actions` : les renommer
-- orpheline les choix déjà enregistrés par les moniteurs.

UPDATE pedagogical_content SET actions = '[{"id":"f17_ballon","label":"Le ballon qu''on lâche","consigne":"Gonflez un ballon et lâchez-le sans le nouer. Demandez pourquoi l''air sort : c''est exactement le mécanisme du vent."},{"id":"f17_fabrique_ou","label":"Il est fabriqué où, le vent ?","consigne":"Posez la question sérieusement. Beaucoup cherchent un endroit. Il n''y en a pas : c''est de l''air qui rééquilibre."},{"id":"f17_fort_ou_faible","label":"Pourquoi fort aujourd''hui","consigne":"Demandez pourquoi il souffle plus fort certains jours. L''écart de pression entre deux zones, rien d''autre."}]'::jsonb WHERE id = '17';
UPDATE pedagogical_content SET actions = '[{"id":"f18_sable_ou_eau","label":"Touche le sable, touche l''eau","consigne":"Faites poser une main sur le sable sec et l''autre dans l''eau. L''écart de température explique la brise à lui seul."},{"id":"f18_pari_heure","label":"Le pari sur l''heure","consigne":"Le matin, faites parier à quelle heure le vent se lèvera. Notez les paris, vérifiez l''après-midi."},{"id":"f18_et_la_nuit","label":"Et la nuit, alors ?","consigne":"Une fois la brise de mer comprise, demandez ce qui se passe la nuit. Le raisonnement s''inverse tout seul."}]'::jsonb WHERE id = '18';
UPDATE pedagogical_content SET actions = '[{"id":"f19_lequel_dangereux","label":"Lequel est le plus traître ?","consigne":"Vent de face qui décoiffe, ou petit vent de dos ? Faites voter. Le petit vent de terre est le vrai piège."},{"id":"f19_test_flottant","label":"L''objet qu''on laisse partir","consigne":"Lâchez un objet flottant près du bord par vent de terre. Sa vitesse de fuite parle mieux qu''un avertissement."},{"id":"f19_ou_je_rentre","label":"Par où tu rentres ?","consigne":"Avant de partir, faites décrire à chacun son chemin de retour compte tenu du vent du jour."}]'::jsonb WHERE id = '19';
UPDATE pedagogical_content SET actions = '[{"id":"f20_tous_le_doigt","label":"Tous le doigt en même temps","consigne":"Au signal, chacun pointe d''où vient le vent. Les doigts divergent, on compare, puis on tranche avec un indice."},{"id":"f20_sans_instrument","label":"Trouvez-en cinq","consigne":"Faites chercher cinq indices du vent sans rien toucher : drapeau, rides, herbes, cheveux, fumée."},{"id":"f20_oreilles_fermees","label":"Les yeux fermés","consigne":"Yeux fermés, chacun tourne sur lui-même jusqu''à sentir le vent bien en face. On rouvre et on compare."}]'::jsonb WHERE id = '20';
UPDATE pedagogical_content SET actions = '[{"id":"f21_comme_au_depart","label":"Toujours pareil qu''au départ ?","consigne":"En milieu de séance, demandez si le vent a changé depuis la mise à l''eau. Peu l''auront suivi."},{"id":"f21_veilleur","label":"Le veilleur du jour","consigne":"Désignez un stagiaire chargé d''annoncer tout changement de vent. Changez de veilleur à chaque séance."},{"id":"f21_chemin_retour","label":"Le retour est-il encore possible ?","consigne":"À mi-séance, faites redire à chacun comment il rentrerait maintenant, avec le vent tel qu''il est."}]'::jsonb WHERE id = '21';
UPDATE pedagogical_content SET actions = '[{"id":"f22_matin_calme","label":"Un matin calme annonce quoi ?","consigne":"Faites parier sur l''après-midi par matin clair et sans vent. La plupart diront journée calme — c''est souvent l''inverse."},{"id":"f22_ingredients","label":"Les ingrédients de la brise","consigne":"Faites lister ce qu''il faut réunir le matin : ciel clair, peu de vent, soleil sur la terre. Vérifiez si c''est le cas."}]'::jsonb WHERE id = '22';
UPDATE pedagogical_content SET actions = '[{"id":"f23_tu_regardes_quoi","label":"Tu regardais quoi ?","consigne":"Après un bord en surpuissance, demandez ce qu''ils ont vu autour d''eux. La réponse est souvent : rien."},{"id":"f23_deux_reglages","label":"Deux bords, deux réglages","consigne":"Un bord sous-toilé, un bord bien réglé. Faites comparer ce qu''ils ont eu le temps de remarquer."}]'::jsonb WHERE id = '23';
UPDATE pedagogical_content SET actions = '[{"id":"f85_air_c_est_rien","label":"L''air, c''est du vide ?","consigne":"Faites-leur dire si l''air est quelque chose. Puis faites courir un sac plastique ouvert : il se remplit et résiste."},{"id":"f85_voile_qui_pousse","label":"Ce qui pousse la voile","consigne":"Faites tenir la voile à deux mains par vent établi. Ce qu''ils sentent pousser n''est pas rien."},{"id":"f85_montre_le_vent","label":"Montre-moi le vent","consigne":"Demandez de montrer le vent lui-même. Impossible — on ne montre que ce qu''il déplace."}]'::jsonb WHERE id = '85';
UPDATE pedagogical_content SET actions = '[{"id":"f102_matin_apres_midi","label":"Ce matin, il venait d''où ?","consigne":"Faites comparer le sens du vent au départ et maintenant. Près de la côte, il s''inverse dans la journée."},{"id":"f102_toujours_meme_cote","label":"Il vient toujours du même côté ?","consigne":"Faites voter. Beaucoup pensent que oui. La brise change de sens entre le jour et la nuit."}]'::jsonb WHERE id = '102';
UPDATE pedagogical_content SET actions = '[{"id":"f121_ecume_qui_gagne","label":"L''écume qui s''étend","consigne":"Montrez l''état de l''eau au départ, faites-la comparer plus tard. De l''écume qui gagne annonce le renforcement."},{"id":"f121_horizon_flou","label":"Regarde l''horizon","consigne":"Faites fixer la ligne d''horizon et dire si elle est nette. Quand elle se voile, quelque chose arrive."},{"id":"f121_on_rentre_quand","label":"On rentre à quel moment ?","consigne":"Faites décider collectivement le signe qui déclenchera le retour. Ils s''y tiennent mieux qu''à une consigne."}]'::jsonb WHERE id = '121';
