-- Actions de terrain : meteo.
--
-- Générées par scripts/importer-actions.mjs. Les actions vivent dans la fiche
-- (`pedagogical_content.actions`), au même titre que l'accroche ou l'idée à retenir.
-- Leurs identifiants sont référencés par `stage_preparations.actions` : les renommer
-- orpheline les choix déjà enregistrés par les moniteurs.

UPDATE pedagogical_content SET actions = '[{"id":"f38_parking_bord_eau","label":"Du parking au bord de l''eau","consigne":"Faites remarquer l''écart de température entre l''arrivée et la mise à l''eau. Demandez qui a pris une couche de plus."},{"id":"f38_habille_pour_ou","label":"Tu t''es habillé pour où ?","consigne":"Demandez sur quelle météo ils se sont habillés : celle du village ou celle d''ici. Ce n''est pas la même."},{"id":"f38_sable_eau_midi","label":"Le sable brûle, pas l''eau","consigne":"En plein soleil, faites toucher le sable puis l''eau. L''eau met des semaines à faire ce que le sable fait en une heure."}]'::jsonb WHERE id = '38';
UPDATE pedagogical_content SET actions = '[{"id":"f39_ou_va_l_eau","label":"Où part l''eau des flaques","consigne":"Montrez une flaque qui sèche sur la cale. Demandez où l''eau est passée, et où elle va finir."},{"id":"f39_il_faut_quoi","label":"Il faut quoi pour faire un nuage","consigne":"Faites lister les ingrédients avant de donner la réponse : de l''eau, de l''air qui monte, du froid, des poussières."}]'::jsonb WHERE id = '39';
UPDATE pedagogical_content SET actions = '[{"id":"f40_ligne_sombre","label":"La ligne sombre au large","consigne":"Faites scruter l''horizon et repérer tout ce qui n''est pas comme le reste : rideau de pluie, changement de couleur."},{"id":"f40_combien_de_temps","label":"Ça met combien de temps ?","consigne":"Faites parier en combien de temps un grain visible au large peut arriver. Les réponses sont toujours trop longues."},{"id":"f40_relais_ciel","label":"Le relais du ciel","consigne":"Un stagiaire est chargé de surveiller l''horizon pendant que les autres naviguent. On change à chaque bord."}]'::jsonb WHERE id = '40';
UPDATE pedagogical_content SET actions = '[{"id":"f41_trois_mots","label":"Le ciel en trois mots","consigne":"Chacun décrit le ciel en trois mots. On compare les mots employés : dégagé, voilé, couvert reviennent."},{"id":"f41_photo_mentale","label":"Le ciel d''il y a une heure","consigne":"Faites décrire le ciel du départ, puis celui de maintenant. C''est l''écart qui annonce, pas l''instantané."}]'::jsonb WHERE id = '41';
UPDATE pedagogical_content SET actions = '[{"id":"f42_plat_ou_tour","label":"Plat ou en tour ?","consigne":"Faites classer les nuages visibles en deux tas : ceux qui s''étalent, ceux qui montent. Seuls les seconds inquiètent."},{"id":"f42_couleur_trompe","label":"La couleur ne dit rien","consigne":"Montrez un nuage gris inoffensif et un blanc qui gonfle. Faites deviner lequel pose problème."},{"id":"f42_dessine_le","label":"Dessine-le du doigt","consigne":"Faites tracer en l''air la silhouette d''un nuage visible. Le geste fixe la forme mieux que le nom."}]'::jsonb WHERE id = '42';
UPDATE pedagogical_content SET actions = '[{"id":"f43_qui_rentre_avant","label":"Qui rentre avant nous","consigne":"Faites repérer si les oiseaux se posent ou rentrent. Ils sentent la dégradation avant nous."},{"id":"f43_pas_que_nous","label":"Sortir au mauvais moment","consigne":"Demandez qui d''autre subit une sortie par temps qui se dégrade. La faune aussi, et elle ne peut pas rentrer."}]'::jsonb WHERE id = '43';
UPDATE pedagogical_content SET actions = '[{"id":"f82_regarde_le_changer","label":"Regarde-le deux minutes","consigne":"Faites fixer un nuage précis pendant deux minutes. Il change de forme sous leurs yeux : rien n''est solide là-dedans."},{"id":"f82_ca_pese_combien","label":"Ça pèse combien ?","consigne":"Faites deviner le poids de l''eau contenue dans un cumulus. Les réponses tournent autour de zéro : c''est environ 500 tonnes."}]'::jsonb WHERE id = '82';
UPDATE pedagogical_content SET actions = '[{"id":"f83_meme_eau","label":"Le blanc et le noir","consigne":"Montrez un nuage blanc et un gris. Demandez ce qui les différencie. Même eau, épaisseur différente."},{"id":"f83_main_devant_soleil","label":"La main devant le soleil","consigne":"Faites regarder à travers une main fine puis un poing fermé. C''est exactement ce que fait l''épaisseur du nuage."}]'::jsonb WHERE id = '83';
UPDATE pedagogical_content SET actions = '[{"id":"f84_d_ou_vient_la_pluie","label":"D''où vient la pluie d''ici","consigne":"Demandez si la pluie qui tombe ici vient de la mer d''ici. Elle peut venir de centaines de kilomètres."},{"id":"f84_suivre_le_nuage","label":"Suis-le du doigt","consigne":"Repérez un nuage formé au-dessus de la mer et suivez sa route vers la terre. Le cycle se voit en direct."}]'::jsonb WHERE id = '84';
UPDATE pedagogical_content SET actions = '[{"id":"f99_il_grossit_ou_pas","label":"Il grossit ou il disparaît ?","consigne":"Choisissez un petit nuage et faites parier sur son sort. On revérifie dix minutes plus tard."},{"id":"f99_air_chaud_monte","label":"Ce qui monte, ce qui reste","consigne":"Faites lever la main à ceux qui pensent que l''air chaud monte. Puis demandez ce qu''il devient plus haut."}]'::jsonb WHERE id = '99';
UPDATE pedagogical_content SET actions = '[{"id":"f100_tous_la_meme_hauteur","label":"Tous à la même hauteur","consigne":"Faites remarquer que les bases des nuages forment une ligne. Demandez pourquoi ils ne descendent pas plus bas."},{"id":"f100_plafond_invisible","label":"Le plafond invisible","consigne":"Faites-leur dire ce qu''il y a à cette altitude précise. Rien de solide : c''est là que l''air devient assez froid."}]'::jsonb WHERE id = '100';
UPDATE pedagogical_content SET actions = '[{"id":"f101_pronostic_du_jour","label":"Le pronostic du ciel","consigne":"À partir des nuages visibles, faites annoncer le temps de la fin de séance. On vérifie en rentrant."},{"id":"f101_voile_ou_amas","label":"Voile ou amas ?","consigne":"Faites trier ce qu''ils voient : voile fin et haut, ou amas qui grossissent. Chacun annonce autre chose."}]'::jsonb WHERE id = '101';
UPDATE pedagogical_content SET actions = '[{"id":"f114_classe_celui_la","label":"Classe-moi celui-là","consigne":"Désignez un nuage et faites répondre aux trois questions : haut ou bas, quelle forme, donne-t-il de la pluie."},{"id":"f114_nom_qui_decrit","label":"Le nom dit tout","consigne":"Donnez « cumulus » et « stratus » et faites deviner lequel est en tas, lequel est en couche. Le mot décrit la forme."}]'::jsonb WHERE id = '114';
UPDATE pedagogical_content SET actions = '[{"id":"f115_enclume","label":"Cherchez l''enclume","consigne":"Faites chercher un sommet aplati en forme d''enclume. C''est la signature du cumulonimbus, visible de très loin."},{"id":"f115_avant_le_tonnerre","label":"On décide avant le bruit","consigne":"Demandez à quel moment on rentre. Beaucoup diront « au premier coup de tonnerre ». Le nuage se voit bien avant."},{"id":"f115_plus_haut_qu_un_avion","label":"Plus haut qu''un avion de ligne","consigne":"Faites estimer la hauteur du nuage. Son sommet dépasse souvent l''altitude où volent les avions : ils le contournent."}]'::jsonb WHERE id = '115';
