-- Actions de terrain : laisse_oiseaux.
--
-- Générées par scripts/importer-actions.mjs. Les actions vivent dans la fiche
-- (`pedagogical_content.actions`), au même titre que l'accroche ou l'idée à retenir.
-- Leurs identifiants sont référencés par `stage_preparations.actions` : les renommer
-- orpheline les choix déjà enregistrés par les moniteurs.

UPDATE pedagogical_content SET actions = '[{"id":"f50_poubelle_ou_garde_manger","label":"Poubelle ou garde-manger ?","consigne":"Demandez ce qu''est cette bande sur le sable. « De la saleté » vient vite. Faites chercher qui vient y manger."},{"id":"f50_jusqu_ou_montee","label":"Elle est montée jusqu''où ?","consigne":"Faites poser la main sur la ligne : c''est exactement là que l''eau s''est arrêtée à la dernière marée haute."}]'::jsonb WHERE id = '50';
UPDATE pedagogical_content SET actions = '[{"id":"f51_deux_tas","label":"Deux tas","consigne":"Faites trier ce qu''on ramasse sur un mètre : ce que la mer a apporté d''un côté, ce qui vient de nous de l''autre."},{"id":"f51_on_enleve_quoi","label":"On enlève quoi ?","consigne":"Une fois les deux tas faits, demandez lequel on emporte. Le désaccord entre eux est le vrai sujet."}]'::jsonb WHERE id = '51';
UPDATE pedagogical_content SET actions = '[{"id":"f52_deux_lignes","label":"Il y en a plusieurs","consigne":"Faites chercher combien de lignes de débris sont visibles. Chacune est une marée précédente."},{"id":"f52_pourquoi_la","label":"Pourquoi si haut aujourd''hui","consigne":"Comparez la ligne du jour à celle d''hier et faites chercher ce qui a changé : coefficient, vent, houle."}]'::jsonb WHERE id = '52';
UPDATE pedagogical_content SET actions = '[{"id":"f53_cinq_choses","label":"Cinq choses différentes","consigne":"Chacun rapporte cinq objets qui ne se ressemblent pas. On étale tout et on nomme ce qu''on peut."},{"id":"f53_oeuf_de_raie","label":"Cherchez la bourse de raie","consigne":"Lancez la chasse à l''œuf de raie ou à l''os de seiche. Trouver l''objet rare accroche mieux qu''une liste."},{"id":"f53_d_ou_ca_vient","label":"Ça vient de qui ?","consigne":"Prenez un objet trouvé et faites remonter à l''animal ou à la plante d''origine. Chaque débris a un propriétaire."}]'::jsonb WHERE id = '53';
UPDATE pedagogical_content SET actions = '[{"id":"f54_comptage_un_metre","label":"Le comptage du mètre","consigne":"Délimitez un mètre de laisse et faites compter d''un côté les éléments naturels, de l''autre les déchets. Le rapport parle seul."},{"id":"f54_bon_ou_mauvais","label":"Bon ou mauvais signe ?","consigne":"Une fois le comptage fait, faites-leur dire si la plage est en bonne santé. Ils tranchent avec leur propre chiffre."}]'::jsonb WHERE id = '54';
UPDATE pedagogical_content SET actions = '[{"id":"f55_avant_de_ramasser","label":"Avant de tout ramasser","consigne":"Annoncez un nettoyage, laissez-les commencer, puis arrêtez-les : demandez ce qu''ils ont mis dans le sac qui ne devait pas y être."},{"id":"f55_a_qui_ca_sert","label":"À qui servent les algues","consigne":"Faites soulever un tas d''algues et regarder ce qui grouille dessous. C''est ce qu''on détruit en ramassant tout."}]'::jsonb WHERE id = '55';
UPDATE pedagogical_content SET actions = '[{"id":"f56_ce_qu_on_a_apporte","label":"Vide ton sac","consigne":"Faites lister ce que le groupe a apporté aujourd''hui, et ce qui repartira en déchet. Le comptage est concret."},{"id":"f56_gourde_ou_bouteille","label":"Une gourde ou dix bouteilles","consigne":"Faites calculer combien de bouteilles une semaine de stage représente pour le groupe entier. Puis comparez aux gourdes."}]'::jsonb WHERE id = '56';
UPDATE pedagogical_content SET actions = '[{"id":"f86_il_est_d_ici","label":"Il est d''ici, celui-là ?","consigne":"Montrez un oiseau et faites parier s''il vit ici toute l''année. Beaucoup ne font que passer."},{"id":"f86_ou_il_dort_en_janvier","label":"Où il dort en janvier","consigne":"Faites imaginer où cet oiseau se trouvait il y a six mois. La Normandie n''est souvent qu''une étape."}]'::jsonb WHERE id = '86';
UPDATE pedagogical_content SET actions = '[{"id":"f87_station_service","label":"Pourquoi ici et pas ailleurs","consigne":"Demandez pourquoi ils s''arrêtent précisément sur cette vasière. Faites chercher ce qu''il y a à manger dedans."},{"id":"f87_ils_fouillent_quoi","label":"Ils cherchent quoi ?","consigne":"Faites observer un oiseau qui sonde la vase et deviner ce qu''il attrape. Puis faites gratter au même endroit."}]'::jsonb WHERE id = '87';
UPDATE pedagogical_content SET actions = '[{"id":"f103_pas_d_autre_endroit","label":"Il peut aller ailleurs ?","consigne":"Demandez ce que fait l''oiseau si sa vasière est occupée. La plupart pensent qu''il ira plus loin. Souvent, il n''y a pas d''ailleurs."},{"id":"f103_cout_du_derangement","label":"Dix fois dans la journée","consigne":"Un oiseau qui s''envole recommence son repas. Faites calculer ce que coûtent dix dérangements sur une journée."}]'::jsonb WHERE id = '103';
UPDATE pedagogical_content SET actions = '[{"id":"f110_ca_disparait","label":"Ça finit par disparaître ?","consigne":"Faites voter. La plupart disent oui. Le plastique ne disparaît pas : il se casse en morceaux de plus en plus petits."},{"id":"f110_sable_a_la_loupe","label":"Le sable de près","consigne":"Faites prendre une poignée de sable et chercher les fragments colorés. Ils sont là, il suffit de regarder."},{"id":"f110_qui_le_mange","label":"Qui finit par l''avaler","consigne":"Reprenez la chaîne alimentaire et faites suivre un fragment du plancton jusqu''à l''assiette."}]'::jsonb WHERE id = '110';
UPDATE pedagogical_content SET actions = '[{"id":"f116_dix_huit_jours","label":"Dix-huit jours plus tôt","consigne":"Faites parier de combien les hirondelles ont avancé leur arrivée en cinquante ans. C''est dix-huit jours."},{"id":"f116_qui_compte","label":"Qui a noté tout ça","consigne":"Demandez comment on sait que les dates changent. Des bénévoles normands notent leurs observations depuis 1972."}]'::jsonb WHERE id = '116';
UPDATE pedagogical_content SET actions = '[{"id":"f117_arriver_trop_tot","label":"Arriver trop tôt","consigne":"Demandez ce qui se passe si l''oiseau arrive avant que sa nourriture soit là. Le problème n''est pas la chaleur, c''est le décalage."},{"id":"f117_chacun_son_rythme","label":"Chacun s''adapte à sa vitesse","consigne":"Faites remarquer que l''oiseau change ses dates, mais pas les insectes au même rythme. C''est l''écart qui pose problème."}]'::jsonb WHERE id = '117';
