-- Corrections du quiz de fin de semaine : dunes_laisse.
--
-- Générées par scripts/importer-quiz.mjs. `data` porte la version adulte, 
-- `data.version_enfant` la version enfant du même sujet. Remplace `version_moniteur`
-- (même rôle, jamais exploité par un vrai choix au lancement avant ce jour).

DELETE FROM game_cards WHERE id = '86a4c74d-967f-4bd9-a813-237ae598ba24';
DELETE FROM game_cards WHERE id = 'd89109de-aed5-4106-9fdb-f38a39168a57';
UPDATE game_cards SET related_objective_id = '50', data = '{"question":"Après la marée haute, il reste une ligne d''algues et de coquillages sur le sable. Comment l''appelle-t-on ?","answers":["La laisse de mer","Des déchets à ramasser","De la mousse","Une trace de bateau"],"correctAnswerIndex":0,"explanation":"C''est la laisse de mer : tout ce que la mer a déposé en se retirant. Ce n''est pas sale — plein de petites bêtes et d''oiseaux y trouvent à manger.","version_enfant":{"question":"Après la marée haute, il reste une ligne d''algues et de coquillages sur le sable. C''est quoi ?","answers":["La laisse de mer","Des déchets à ramasser","De la mousse","Une trace de bateau"],"correctAnswerIndex":0,"explanation":"C''est la laisse de mer : tout ce que la mer a déposé en se retirant. Ce n''est pas sale — plein de petites bêtes et d''oiseaux y trouvent à manger."}}'::jsonb WHERE id = '919ddcb8-2486-42f3-bab8-ba29a72b4191';
UPDATE game_cards SET related_objective_id = '110', data = '{"question":"Pourquoi la gestion des déchets plastiques est-elle un enjeu majeur pour le milieu marin ?","answers":["Uniquement pour des raisons esthétiques","Ils persistent des siècles, se fragmentent en microplastiques et entrent dans la chaîne alimentaire","Ils bloquent uniquement les hélices des bateaux","Le milieu marin les neutralise en quelques années"],"correctAnswerIndex":1,"explanation":"Un plastique en mer met des décennies, parfois des siècles, à se dégrader. En se fragmentant, il devient microplastique, ingéré par le plancton puis toute la chaîne alimentaire.","version_enfant":{"question":"Un plastique jeté à la mer, il finit par disparaître ?","answers":["Oui, il fond dans l''eau","Non, il se casse en morceaux de plus en plus petits","Oui, en quelques jours","Oui, les poissons le mangent et il disparaît"],"correctAnswerIndex":1,"explanation":"Le plastique ne disparaît pas : il se casse en morceaux de plus en plus petits, que les animaux avalent."}}'::jsonb WHERE id = 'b148c8f6-b764-485f-b323-9b7af3620641';
UPDATE game_cards SET related_objective_id = '48', data = '{"question":"Pourquoi les dunes sont-elles fragiles ?","answers":["Le sable est trop fin et s''envole facilement","Le piétinement détruit la végétation qui retient le sable, déclenchant l''érosion","L''eau de mer les dissout progressivement","Les dunes sont en fait très solides"],"correctAnswerIndex":1,"explanation":"Les racines des plantes dunaires retiennent le sable comme un filet. Le piétinement répété tasse le sol et abîme ces plantes ; sans elles, le sable redevient mobile.","version_enfant":{"question":"Pourquoi il ne faut pas marcher partout sur la dune ?","answers":["Parce que le sable est trop chaud","Parce que ça abîme les plantes qui retiennent le sable","Parce que c''est interdit sans raison","Parce qu''il y a des serpents"],"correctAnswerIndex":1,"explanation":"Les racines des plantes tiennent le sable comme un filet. Si on les abîme en marchant dessus, le sable repart avec le vent."}}'::jsonb WHERE id = '202d3adb-6ecf-4b10-b342-1c45083d9d80';
UPDATE game_cards SET related_objective_id = '44', data = '{"question":"Comment se forment les dunes côtières ?","answers":["Par érosion des falaises par les vagues","Par accumulation de sable transporté par le vent, piégé par les plantes pionnières","Par dépôt de sédiments fluviaux uniquement","Par action directe des marées sur le sable"],"correctAnswerIndex":1,"explanation":"Le sable transporté par le vent est piégé par les plantes pionnières (oyat, chiendent des sables), première ligne de fixation.","version_enfant":{"question":"Comment naît une dune ?","answers":["Le vent pousse le sable, qui s''arrête derrière une touffe d''herbe et s''accumule","La mer la construit directement avec les vagues","Elle est toujours là, depuis toujours","Les gens l''empilent avec des pelles"],"correctAnswerIndex":0,"explanation":"Le vent porte le sable. Dès qu''il rencontre une plante, le sable s''arrête et s''accumule : la dune grandit, grain par grain."}}'::jsonb WHERE id = '8eb27fbf-0b05-4d1b-8e28-6647e0acb65c';
UPDATE game_cards SET related_objective_id = '49', data = '{"question":"Qu''est-ce que le recul du trait de côte ?","answers":["Le mouvement normal de la marée qui couvre et découvre la plage","Le recul progressif de la limite terre/mer par érosion, accéléré par la montée des eaux et les tempêtes","La progression des dunes vers l''intérieur des terres","L''affaissement du fond marin"],"correctAnswerIndex":1,"explanation":"Le recul du trait de côte est ancien, mais il s''accélère : la montée du niveau des mers et des tempêtes plus fréquentes rongent le littoral plus vite qu''il ne peut se reconstituer.","version_enfant":{"question":"Le fait que la côte recule, c''est un phénomène récent ?","answers":["Oui, ça vient de commencer","Non, c''est ancien, mais ça va de plus en plus vite","Non, ça n''existe pas vraiment","Oui, à cause des bateaux"],"correctAnswerIndex":1,"explanation":"Les côtes ont toujours bougé, mais ça s''accélère : la mer monte et les tempêtes sont plus fortes qu''avant."}}'::jsonb WHERE id = '8c711f2a-85eb-4dcf-b5c1-ecb6d415d475';
