-- Corrections du quiz de fin de semaine : cohabiter.
--
-- Générées par scripts/importer-quiz.mjs. `data` porte la version adulte, 
-- `data.version_enfant` la version enfant du même sujet. Remplace `version_moniteur`
-- (même rôle, jamais exploité par un vrai choix au lancement avant ce jour).

UPDATE game_cards SET related_objective_id = '57', data = '{"question":"Pourquoi le littoral est-il un milieu particulièrement riche en biodiversité ?","answers":["Parce que l''eau y est plus chaude qu''au large","C''est un écotone, une zone de rencontre terre/mer qui multiplie habitats et ressources","Parce que les vagues apportent des nutriments du fond","Uniquement parce qu''il y a moins de prédateurs"],"correctAnswerIndex":1,"explanation":"Le littoral est un écotone : une zone de transition qui combine les ressources des deux milieux, terre et mer.","version_enfant":{"question":"Une plage, c''est un endroit vide ?","answers":["Oui, il n''y a presque rien","Non, c''est un des endroits les plus riches en vie qui soient","Oui, sauf en été","Ça dépend des plages seulement"],"correctAnswerIndex":1,"explanation":"Le littoral est un carrefour entre la terre et la mer. Deux mondes qui se rencontrent, ça fait beaucoup plus de vie — même si elle est discrète."}}'::jsonb WHERE id = '4d90379f-2de9-43dc-8d02-b933481d9385';
UPDATE game_cards SET related_objective_id = '73', data = '{"question":"Quelle est la règle d''or pour limiter son impact sur le littoral ?","answers":["Ramasser uniquement les déchets plastiques","Ne rien laisser derrière soi et respecter les chemins balisés","Éviter d''aller à la plage hors des zones aménagées","Observer mais ne jamais toucher"],"correctAnswerIndex":1,"explanation":"''Ne rien laisser derrière soi'', combiné au respect des chemins balisés et des distances d''observation, résume l''essentiel de la pratique responsable.","version_enfant":{"question":"Quelle est la règle la plus simple pour ne pas abîmer la plage ?","answers":["Ne rien laisser derrière soi en partant","Ramasser tout ce qu''on trouve, même les algues","Ne jamais y aller","Marcher toujours au même endroit"],"correctAnswerIndex":0,"explanation":"Ne rien laisser derrière soi, c''est la règle la plus simple et la plus efficace."}}'::jsonb WHERE id = '53da99a0-a7f1-48f9-a585-bfd742800fe4';
UPDATE game_cards SET related_objective_id = '64', data = '{"question":"Pourquoi un dérangement de la faune peut-il causer du tort aux animaux ?","answers":["Uniquement parce que les animaux ont peur du bruit","Fuir dépense une énergie précieuse ; en période de reproduction, ça peut mener à l''abandon des œufs","Les animaux s''habituent rapidement sans conséquence","Seuls les oiseaux sont sensibles au dérangement"],"correctAnswerIndex":1,"explanation":"Chaque fuite coûte de l''énergie à un animal. En période de reproduction, un dérangement répété peut conduire à l''abandon des petits.","version_enfant":{"question":"Un oiseau qui s''envole quand tu approches, puis qui revient : tout va bien ?","answers":["Oui, il n''a rien perdu","Non, il a dépensé une énergie qu''il ne récupère pas forcément","Oui, ça ne lui coûte rien","Non, il ne reviendra jamais"],"correctAnswerIndex":1,"explanation":"Chaque fuite coûte de l''énergie à l''animal — celle dont il a besoin pour se nourrir et élever ses petits."}}'::jsonb WHERE id = '8ad89634-29ea-4194-ae42-29055f065a60';
UPDATE game_cards SET related_objective_id = '62', data = '{"question":"Comment observer la faune littorale sans la déranger ?","answers":["S''approcher le plus possible pour bien voir","Rester à distance, ne pas faire de bruit — le dérangement commence dès le premier changement de comportement","Faire du bruit pour que les animaux restent immobiles","Observer uniquement les espèces protégées"],"correctAnswerIndex":1,"explanation":"Le dérangement commence dès qu''un animal change de comportement, bien avant qu''il fuie. Rester discret et à distance préserve l''animal.","version_enfant":{"question":"Un animal ne s''envole pas quand tu t''approches : tout va bien ?","answers":["Oui, s''il ne s''envole pas c''est qu''il va bien","Pas forcément — s''il arrête de manger et te regarde, c''est déjà trop près","Oui, seule la fuite compte","Non, il faut toujours qu''il s''envole"],"correctAnswerIndex":1,"explanation":"Le dérangement commence bien avant la fuite. Un animal qui cesse de manger et vous fixe, c''est déjà trop près."}}'::jsonb WHERE id = 'd44f29e4-4679-49b1-90df-e8504abefc87';
