-- Actions de terrain : observer_activites.
--
-- Générées par scripts/importer-actions.mjs. Les actions vivent dans la fiche
-- (`pedagogical_content.actions`), au même titre que l'accroche ou l'idée à retenir.
-- Leurs identifiants sont référencés par `stage_preparations.actions` : les renommer
-- orpheline les choix déjà enregistrés par les moniteurs.

UPDATE pedagogical_content SET actions = '[{"id":"f68_qui_decide_l_heure","label":"Qui décide de l''heure","consigne":"Demandez qui fixe l''heure de départ. Beaucoup diront le club. C''est la marée, et elle bouge chaque jour."},{"id":"f68_demain_a_quelle_heure","label":"Demain, à quelle heure ?","consigne":"Faites calculer l''heure de départ de demain à partir de celle d''aujourd''hui. Cinquante minutes de plus."}]'::jsonb WHERE id = '68';
UPDATE pedagogical_content SET actions = '[{"id":"f69_chaine_visible","label":"La chaîne sous nos yeux","consigne":"Faites relier ce qui est visible ici : le vent, le sable déplacé, la plante qui le retient, l''animal qui s''y cache."},{"id":"f69_on_enleve_quoi","label":"On enlève un maillon","consigne":"Une fois la chaîne posée, retirez un élément — la plante, par exemple — et faites décrire ce qui s''écroule."}]'::jsonb WHERE id = '69';
UPDATE pedagogical_content SET actions = '[{"id":"f70_cinq_minutes_avant","label":"Le tour d''horizon","consigne":"Avant la mise à l''eau, faites annoncer les quatre points : vent, mer, nuages, marée. Chacun en prend un."},{"id":"f70_il_fait_beau_donc","label":"Il fait beau, donc ça va ?","consigne":"Faites voter si le soleil suffit à décider. Le vent et la marée comptent bien plus."}]'::jsonb WHERE id = '70';
UPDATE pedagogical_content SET actions = '[{"id":"f71_choisis_ton_amer","label":"Choisis ton amer","consigne":"Chacun désigne un point fixe à terre et le garde toute la séance. On vérifie qu''il est encore visible du large."},{"id":"f71_la_bouee_bouge","label":"Pourquoi pas la bouée ?","consigne":"Faites proposer des repères. Quand quelqu''un dit « la bouée », demandez si elle est vraiment fixe."}]'::jsonb WHERE id = '71';
UPDATE pedagogical_content SET actions = '[{"id":"f72_qu_est_ce_qui_detonne","label":"Qu''est-ce qui détonne ici","consigne":"Faites chercher une chose qui n''a rien à faire là : engin abandonné, animal en détresse, couleur d''eau anormale."},{"id":"f72_quelqu_un_l_a_dit","label":"Quelqu''un l''a déjà signalé ?","consigne":"Devant quelque chose d''anormal, demandez qui pense que ça a déjà été signalé. Souvent, personne ne l''a fait."}]'::jsonb WHERE id = '72';
UPDATE pedagogical_content SET actions = '[{"id":"f73_avant_apres_photo","label":"Avant et après nous","consigne":"Faites mémoriser l''état de l''endroit en arrivant. Au départ, on compare. La différence doit être nulle."},{"id":"f73_un_petit_dechet","label":"Un tout petit déchet","consigne":"Faites estimer combien de personnes passent ici cet été, puis multipliez par un seul déchet chacune."}]'::jsonb WHERE id = '73';
UPDATE pedagogical_content SET actions = '[{"id":"f74_chemin_le_plus_court","label":"Le chemin le plus court","consigne":"Faites tracer le trajet le plus direct, puis chercher ce qu''il traverse. Le raccourci passe par le plus fragile."},{"id":"f74_contourner_ou_traverser","label":"On contourne quoi","consigne":"Faites lister les zones à éviter avant de se mettre en route : mares, algues, laisse de mer, dune."}]'::jsonb WHERE id = '74';
UPDATE pedagogical_content SET actions = '[{"id":"f75_qui_travaille_ici","label":"Qui travaille ici","consigne":"Faites lister ceux qui gagnent leur vie sur cette plage ou dans cette eau. La liste dépasse ce qu''ils imaginent."},{"id":"f75_traces_d_usage","label":"Les traces des autres","consigne":"Faites chercher ce qui trahit un usage : parcs à huîtres, bouées de mouillage, casiers, cabane."}]'::jsonb WHERE id = '75';
UPDATE pedagogical_content SET actions = '[{"id":"f76_notre_trace_du_jour","label":"Notre trace à nous","consigne":"En fin de séance, faites lister ce que le groupe a laissé : empreintes, bruit, zones piétinées, déchets."},{"id":"f76_petit_donc_inoffensif","label":"Petit, donc inoffensif ?","consigne":"Montrez un gros déchet et un fragment minuscule. Faites deviner lequel pose le plus de problèmes."}]'::jsonb WHERE id = '76';
UPDATE pedagogical_content SET actions = '[{"id":"f77_dans_cinquante_ans","label":"Et dans cinquante ans ?","consigne":"Prenez une activité visible et demandez si elle sera encore possible dans cinquante ans, et à quelle condition."},{"id":"f77_mer_vide","label":"Une mer vidée","consigne":"Faites imaginer ce que deviennent les pêcheurs si la mer se vide. Économie et environnement ne s''opposent pas."}]'::jsonb WHERE id = '77';
UPDATE pedagogical_content SET actions = '[{"id":"f78_regarde_le_materiel","label":"Regarde le matériel du club","consigne":"Faites chercher ce qui a changé ici : matériaux, mouillages, zones balisées. Beaucoup est déjà en place."},{"id":"f78_rien_ne_bouge","label":"Rien ne change jamais ?","consigne":"Laissez-les dire que rien ne bouge, puis faites l''inventaire de ce qui a déjà évolué autour d''eux."}]'::jsonb WHERE id = '78';
UPDATE pedagogical_content SET actions = '[{"id":"f79_vide_ton_sac","label":"Vide ton sac","consigne":"Faites sortir ce que chacun a apporté et trier : jetable ou réutilisable. Le comptage est immédiat."},{"id":"f79_loin_de_la_mer","label":"Agir loin de la mer","consigne":"Demandez ce qu''on peut faire pour l''océan depuis chez soi, à cent kilomètres d''ici. La liste existe."}]'::jsonb WHERE id = '79';
UPDATE pedagogical_content SET actions = '[{"id":"f80_photo_qui_compte","label":"La photo qui compte","consigne":"Faites photographier une espèce avec le lieu et la date. Ces trois infos en font une donnée scientifique."},{"id":"f80_faut_etre_expert","label":"Il faut être expert ?","consigne":"Faites voter. Non : une photo bien située vaut déjà beaucoup, l''identification peut venir après."}]'::jsonb WHERE id = '80';
UPDATE pedagogical_content SET actions = '[{"id":"f81_combien_d_yeux","label":"Combien d''yeux sur cette plage","consigne":"Faites estimer combien de personnes passent ici par jour, puis combien de scientifiques. Le rapport parle."},{"id":"f81_ce_qu_on_voit_et_pas_eux","label":"Ce qu''on voit et pas eux","consigne":"Faites lister ce que le groupe a observé aujourd''hui. Aucun chercheur n''était là pour le voir."}]'::jsonb WHERE id = '81';
UPDATE pedagogical_content SET actions = '[{"id":"f92_pourquoi_comme_ca","label":"Pourquoi c''est comme ça ?","consigne":"Chacun désigne une chose qui l''intrigue et pose sa question. On n''y répond pas tout de suite."},{"id":"f92_regarder_ou_observer","label":"Regarder ou observer ?","consigne":"Faites la différence à voix haute : tout le monde regarde. Observer, c''est se demander pourquoi."}]'::jsonb WHERE id = '92';
UPDATE pedagogical_content SET actions = '[{"id":"f93_ferme_les_yeux","label":"Une minute les yeux fermés","consigne":"Yeux fermés, chacun compte les sons différents qu''il entend. On rouvre et on met en commun."},{"id":"f93_ca_sent_quoi","label":"Ça sent quoi ici ?","consigne":"Faites nommer les odeurs : algues, vase, sel. Elles changent avec la marée, et elles renseignent."}]'::jsonb WHERE id = '93';
UPDATE pedagogical_content SET actions = '[{"id":"f94_l_ordinaire_d_abord","label":"Ce qu''on voit à chaque fois","consigne":"Faites lister les espèces vues à chaque séance. C''est cette liste qui permettra de repérer l''inhabituel."},{"id":"f94_qu_est_ce_qui_change","label":"Qu''est-ce qui a changé","consigne":"En fin de semaine, faites comparer avec la première séance. Ce qui a changé n''apparaît qu''aux habitués."}]'::jsonb WHERE id = '94';
UPDATE pedagogical_content SET actions = '[{"id":"f95_il_s_est_fige","label":"Il s''est figé","consigne":"Approchez d''un animal et faites dire stop au moment où il se fige. C''est la limite, elle est fixée par lui."},{"id":"f95_mieux_voir_ou_deranger","label":"Pour mieux voir","consigne":"Demandez qui a envie de s''approcher davantage. Puis ce que ça coûte à l''animal de reculer."}]'::jsonb WHERE id = '95';
UPDATE pedagogical_content SET actions = '[{"id":"f105_meme_sens_ou_pas","label":"Ils vont dans le même sens ?","consigne":"Faites comparer la direction du vent et celle des vagues. En opposition, la mer devient courte et hachée."},{"id":"f105_pourquoi_ca_secoue","label":"Pourquoi ça secoue autant","consigne":"Par mer hachée, faites chercher l''explication. Ce n''est pas la force du vent, c''est son désaccord avec la houle."}]'::jsonb WHERE id = '105';
UPDATE pedagogical_content SET actions = '[{"id":"f106_trois_questions","label":"Les trois questions du départ","consigne":"Avant de partir : heure de la prochaine marée, coefficient, zones de courant fort. Chacun en prend une."},{"id":"f106_l_heure_suffit_pas","label":"L''heure suffit ?","consigne":"Demandez si connaître l''heure de la marée suffit. Sans le coefficient, on ne sait pas si le courant sera gérable."}]'::jsonb WHERE id = '106';
UPDATE pedagogical_content SET actions = '[{"id":"f109_a_quelle_vitesse","label":"Ça repousse à quelle vitesse","consigne":"Prenez une ressource prélevée ici et faites estimer son temps de renouvellement. Puis la vitesse de prélèvement."},{"id":"f109_renouvelable_donc_infini","label":"Renouvelable, donc infini ?","consigne":"Faites voter. Tout dépend du rythme : plus vite qu''elle ne repousse, une ressource renouvelable s''épuise."}]'::jsonb WHERE id = '109';
UPDATE pedagogical_content SET actions = '[{"id":"f120_cinq_minutes_du_bord","label":"Cinq minutes depuis le bord","consigne":"Personne ne bouge pendant cinq minutes. On repère les séries, où ça casse, et la zone la plus calme."},{"id":"f120_un_coup_d_oeil_suffit","label":"Un coup d''œil suffit ?","consigne":"Faites juger la mer en trois secondes, puis après cinq minutes. Les grosses séries ne se voient qu''en attendant."}]'::jsonb WHERE id = '120';
UPDATE pedagogical_content SET actions = '[{"id":"f125_savoir_ou_faire","label":"Tu le savais déjà ?","consigne":"Sur un geste connu de tous, demandez qui le savait, puis qui le fait vraiment. L''écart est le sujet."}]'::jsonb WHERE id = '125';
UPDATE pedagogical_content SET actions = '[{"id":"f126_ce_qu_on_change_ce_soir","label":"Ce que je change ce soir","consigne":"Chacun nomme une chose qu''il fera différemment dès aujourd''hui. On y revient à la séance suivante."},{"id":"f126_comprendre_suffit","label":"Comprendre, ça suffit ?","consigne":"Faites voter si savoir suffit à régler un problème. Beaucoup savent ; peu changent quelque chose."}]'::jsonb WHERE id = '126';
UPDATE pedagogical_content SET actions = '[{"id":"f127_tout_est_foutu","label":"C''est foutu de toute façon ?","consigne":"Laissez sortir le découragement, puis faites chercher ce qui s''est déjà amélioré ici. Il y a des exemples."},{"id":"f127_ce_qui_depend_de_nous","label":"Ce qui dépend encore de nous","consigne":"Faites trier : ce qui est déjà joué, et ce qui dépend des décisions à venir. La deuxième liste est longue."}]'::jsonb WHERE id = '127';
