-- Actions de terrain : courants_vagues.
--
-- Générées par scripts/importer-actions.mjs. Les actions vivent dans la fiche
-- (`pedagogical_content.actions`), au même titre que l'accroche ou l'idée à retenir.
-- Leurs identifiants sont référencés par `stage_preparations.actions` : les renommer
-- orpheline les choix déjà enregistrés par les moniteurs.

UPDATE pedagogical_content SET actions = '[{"id":"f24_vent_ou_maree","label":"Vent ou marée ?","consigne":"Faites voter sur ce qui pousse l''eau ici. Beaucoup diront le vent. Près des côtes, c''est surtout la marée."},{"id":"f24_meme_sens","label":"Ils vont dans le même sens ?","consigne":"Faites comparer le sens du vent et celui du courant autour d''une bouée. Souvent, ils divergent."}]'::jsonb WHERE id = '24';
UPDATE pedagogical_content SET actions = '[{"id":"f25_et_dans_six_heures","label":"Et dans six heures ?","consigne":"Une fois le courant repéré, faites prédire son sens en fin d''après-midi. Celui de marée s''inverse."},{"id":"f25_trois_sortes","label":"Lequel on a devant nous","consigne":"Trois courants possibles : marée, dérive, grand courant. Faites-leur trancher lequel domine aujourd''hui."}]'::jsonb WHERE id = '25';
UPDATE pedagogical_content SET actions = '[{"id":"f26_rame_sans_avancer","label":"Rame et regarde à terre","consigne":"Faites pagayer à contre-courant en fixant un repère à terre. L''effort ne se traduit pas en distance."},{"id":"f26_aller_retour_chrono","label":"L''aller et le retour","consigne":"Même trajet dans les deux sens, chronométré. L''écart entre les deux temps, c''est le courant."}]'::jsonb WHERE id = '26';
UPDATE pedagogical_content SET actions = '[{"id":"f27_moustache_bouee","label":"La moustache de la bouée","consigne":"Faites chercher la traînée d''écume derrière une bouée ou un piquet. Elle pointe le sens du courant."},{"id":"f27_sans_rien_jeter","label":"Sans rien jeter à l''eau","consigne":"Interdisez de jeter quoi que ce soit et demandez le sens du courant. Les obstacles déjà en place suffisent."}]'::jsonb WHERE id = '27';
UPDATE pedagogical_content SET actions = '[{"id":"f28_tu_le_sens","label":"Tu le sens, le courant ?","consigne":"Demandez-leur, une fois portés par le courant, s''ils le sentent. Non — et c''est exactement le piège."},{"id":"f28_retour_possible","label":"Le retour te coûtera quoi","consigne":"Avant de partir avec le courant, faites estimer l''effort du retour. On repart souvent trop loin."}]'::jsonb WHERE id = '28';
UPDATE pedagogical_content SET actions = '[{"id":"f29_ca_va_ou","label":"Ça part où ?","consigne":"Montrez un débris qui dérive et faites imaginer où il sera demain. Le courant ne fait pas disparaître."},{"id":"f29_autoroute","label":"Qui d''autre voyage là-dedans","consigne":"Faites lister ce que le courant transporte en plus de l''eau : plancton, larves, nourriture."}]'::jsonb WHERE id = '29';
UPDATE pedagogical_content SET actions = '[{"id":"f30_vent_fort_vagues","label":"Il souffle depuis quand ?","consigne":"Faites relier la taille des vagues du jour à la force du vent, puis demandez depuis combien de temps il souffle."},{"id":"f30_vague_ou_maree","label":"Vague ou marée ?","consigne":"Faites distinguer les deux. La marée, c''est la Lune et ça dure six heures. La vague, c''est le vent et ça dure trois secondes."}]'::jsonb WHERE id = '30';
UPDATE pedagogical_content SET actions = '[{"id":"f31_range_ou_pas","label":"En rang ou en désordre ?","consigne":"Faites observer si les vagues sont alignées et espacées, ou courtes et anarchiques. La réponse dit d''où elles viennent."},{"id":"f31_pas_de_vent_pourtant","label":"Des vagues sans vent","consigne":"Par temps calme avec de la houle, demandez d''où viennent ces vagues puisqu''il n''y a pas de vent ici."}]'::jsonb WHERE id = '31';
UPDATE pedagogical_content SET actions = '[{"id":"f32_pourquoi_la_ligne","label":"Pourquoi elles cassent là","consigne":"Montrez la ligne de déferlement et demandez ce qu''elle indique. C''est l''endroit où le fond remonte."},{"id":"f32_trop_grosse","label":"Elle casse parce qu''elle est grosse ?","consigne":"Faites voter. La plupart diront oui. Elle casse parce que l''eau devient trop peu profonde sous elle."}]'::jsonb WHERE id = '32';
UPDATE pedagogical_content SET actions = '[{"id":"f33_moutons_ou_pas","label":"Cherchez les moutons","consigne":"Faites chercher l''écume blanche sur les crêtes. Elle apparaît à partir d''un vent précis : c''est un vrai indice."},{"id":"f33_un_seul_mot","label":"La mer en un mot","consigne":"Chacun choisit un mot : plate, ridée, clapoteuse, agitée. On compare et on se met d''accord sur un seul."}]'::jsonb WHERE id = '33';
UPDATE pedagogical_content SET actions = '[{"id":"f34_compte_entre_deux","label":"Compte entre deux vagues","consigne":"Faites compter les secondes entre deux crêtes. Court et creux, ou long et doux : ça ne se pilote pas pareil."},{"id":"f34_haute_ou_creuse","label":"Haute ou creuse ?","consigne":"Montrez une vague haute et douce, puis une petite et raide. Faites deviner laquelle pose problème."}]'::jsonb WHERE id = '34';
UPDATE pedagogical_content SET actions = '[{"id":"f35_avant_apres","label":"Avant et après le rouleau","consigne":"Faites observer une même vague avant qu''elle casse, puis après. Elle soulève, puis elle pousse."},{"id":"f35_ou_ca_casse","label":"Repère où ça casse","consigne":"Avant de s''engager, faites repérer la zone de déferlement et le passage le plus calme."}]'::jsonb WHERE id = '35';
UPDATE pedagogical_content SET actions = '[{"id":"f36_meme_vague","label":"C''est la même eau","consigne":"Faites suivre une vague du large jusqu''au déferlement. Houle et vague sont deux moments du même mouvement."}]'::jsonb WHERE id = '36';
UPDATE pedagogical_content SET actions = '[{"id":"f37_souleve_une_algue","label":"Soulève et regarde","consigne":"Faites soulever doucement un paquet d''algues sur un rocher. Ce qui grouille dessous est ce qu''on écrase en marchant."},{"id":"f37_par_ou_on_passe","label":"Par où on passe","consigne":"Avant de traverser les rochers, faites choisir collectivement le trajet. Ils défendent leur itinéraire."}]'::jsonb WHERE id = '37';
UPDATE pedagogical_content SET actions = '[{"id":"f89_ou_sont_les_berges","label":"Où sont les berges ?","consigne":"Faites comparer à une rivière. Un courant marin n''a ni lit ni berges : on ne le voit qu''à ce qu''il déplace."},{"id":"f89_montre_le","label":"Montre-moi le courant","consigne":"Demandez de le montrer du doigt. Impossible directement — il faut passer par un objet qui dérive ou un remous."}]'::jsonb WHERE id = '89';
UPDATE pedagogical_content SET actions = '[{"id":"f90_d_ou_elle_vient","label":"Elle vient d''où, celle-là","consigne":"Faites estimer la distance parcourue par la houle du jour. Souvent des centaines de kilomètres."},{"id":"f90_mise_en_rang","label":"Pourquoi elles sont en rang","consigne":"Demandez pourquoi la houle est régulière alors qu''une tempête est chaotique. Le voyage les a triées."}]'::jsonb WHERE id = '90';
UPDATE pedagogical_content SET actions = '[{"id":"f104_trois_ingredients","label":"Les trois ingrédients","consigne":"Faites deviner ce qu''il faut pour de grosses vagues. Ils diront « du vent fort ». Il en faut trois : force, durée, distance."},{"id":"f104_lequel_manque","label":"Lequel manque aujourd''hui","consigne":"Une fois les trois connus, faites chercher lequel fait défaut pour expliquer la mer du jour."}]'::jsonb WHERE id = '104';
UPDATE pedagogical_content SET actions = '[{"id":"f108_chrono_deux_cretes","label":"Le chrono entre deux crêtes","consigne":"Faites chronométrer le temps entre deux vagues au même point. Dix secondes ou plus signent une houle venue de loin."},{"id":"f108_basse_mais_puissante","label":"Basse mais puissante","consigne":"Faites juger la mer sur la hauteur seule, puis sur la période. Une houle longue et basse porte plus d''énergie."}]'::jsonb WHERE id = '108';
UPDATE pedagogical_content SET actions = '[{"id":"f118_pourquoi_les_oiseaux_la","label":"Pourquoi ils sont tous là","consigne":"Faites repérer un rassemblement d''oiseaux en mer et chercher pourquoi à cet endroit précis."},{"id":"f118_meme_partout","label":"La mer est pleine partout ?","consigne":"Faites voter. La vie se concentre là où les courants font remonter la nourriture des profondeurs."}]'::jsonb WHERE id = '118';
UPDATE pedagogical_content SET actions = '[{"id":"f119_pas_tout_a_fait_le_vent","label":"Pas tout à fait dans le vent","consigne":"Faites comparer le sens du vent et celui du courant de surface. L''écart vient de la rotation de la Terre."},{"id":"f119_la_cote_devie","label":"La côte le détourne","consigne":"Sur une carte, faites suivre le courant le long de la côte. Sa forme le canalise autant que le vent le pousse."}]'::jsonb WHERE id = '119';
UPDATE pedagogical_content SET actions = '[{"id":"f122_le_vent_tombe","label":"Le vent tombe, et après ?","consigne":"Demandez ce qui arrive aux vagues si le vent s''arrête maintenant. Celles du vent meurent, la houle continue."}]'::jsonb WHERE id = '122';
UPDATE pedagogical_content SET actions = '[{"id":"f123_de_face_ou_de_biais","label":"De face ou de biais ?","consigne":"Faites observer l''angle des vagues par rapport à la plage. De biais, elles déplacent le sable le long de la côte."},{"id":"f123_deux_plages","label":"Deux plages, même houle","consigne":"Comparez deux endroits d''orientation différente le même jour. La même houle n''y produit pas les mêmes vagues."}]'::jsonb WHERE id = '123';
UPDATE pedagogical_content SET actions = '[{"id":"f124_attends_les_series","label":"Attends les séries","consigne":"Faites observer cinq minutes avant de juger. Les grosses arrivent groupées, avec des accalmies entre."},{"id":"f124_calme_ici_pourtant","label":"Pourtant il fait beau","consigne":"Par beau temps avec de la houle, demandez pourquoi la mer est formée. La tempête est ailleurs."}]'::jsonb WHERE id = '124';
