-- Actions de terrain : etat_dunes_cohabiter.
--
-- Générées par scripts/importer-actions.mjs. Les actions vivent dans la fiche
-- (`pedagogical_content.actions`), au même titre que l'accroche ou l'idée à retenir.
-- Leurs identifiants sont référencés par `stage_preparations.actions` : les renommer
-- orpheline les choix déjà enregistrés par les moniteurs.

UPDATE pedagogical_content SET actions = '[{"id":"f44_derriere_chaque_obstacle","label":"Derrière chaque obstacle","consigne":"Faites chercher les petits amas de sable derrière les touffes et les bois flottés. Chacun est une dune qui commence."},{"id":"f44_depuis_toujours","label":"Elles sont là depuis quand ?","consigne":"Demandez depuis combien de temps la dune existe. Elle se construit encore, grain par grain, aujourd''hui."}]'::jsonb WHERE id = '44';
UPDATE pedagogical_content SET actions = '[{"id":"f45_marche_et_regarde","label":"Vingt pas vers l''intérieur","consigne":"Faites marcher de la plage vers l''intérieur en nommant chaque changement de végétation. Les étages apparaissent."},{"id":"f45_pourquoi_ca_change","label":"Pourquoi ça change","consigne":"Une fois les étages repérés, demandez ce qui change entre eux. Le vent et le sel, de moins en moins forts."}]'::jsonb WHERE id = '45';
UPDATE pedagogical_content SET actions = '[{"id":"f46_carte_identite","label":"La carte d''identité de la plage","consigne":"Faites décrire la plage en cinq points : sable, galets, dunes, largeur, exposition. Comparez avec une autre plage connue."},{"id":"f46_grain_de_sable","label":"Le sable de près","consigne":"Faites prendre une poignée et regarder le grain. Fin ou grossier, il dit la force des vagues ici."}]'::jsonb WHERE id = '46';
UPDATE pedagogical_content SET actions = '[{"id":"f47_falaise_de_sable","label":"La petite falaise","consigne":"Cherchez au pied de la dune une coupure verticale et fraîche. C''est la dernière tempête qui l''a taillée."},{"id":"f47_meme_endroit_vendredi","label":"Le même endroit vendredi","consigne":"Choisissez un repère au pied de la dune et revenez-y en fin de semaine. On mesure ce qui a bougé."}]'::jsonb WHERE id = '47';
UPDATE pedagogical_content SET actions = '[{"id":"f48_tire_sur_l_oyat","label":"Tire doucement sur l''oyat","consigne":"Faites tirer doucement une touffe et sentir la résistance. Les racines tiennent le sable comme un filet."},{"id":"f48_chemin_sauvage","label":"Qui a fait ce chemin","consigne":"Montrez un passage creusé dans la dune et demandez comment il s''est formé. Des pas répétés, rien d''autre."}]'::jsonb WHERE id = '48';
UPDATE pedagogical_content SET actions = '[{"id":"f49_blockhaus_dans_l_eau","label":"Ce qui n''était pas dans l''eau","consigne":"Cherchez un blockhaus, un escalier ou un arbre déchaussé. Chacun marque où était la côte avant."},{"id":"f49_nouveau_ou_pas","label":"C''est nouveau ?","consigne":"Faites voter : le recul du trait de côte est-il récent ? Non — c''est sa vitesse qui a changé."}]'::jsonb WHERE id = '49';
UPDATE pedagogical_content SET actions = '[{"id":"f57_combien_de_milieux","label":"Combien de milieux d''ici","consigne":"Sans bouger, faites compter les milieux visibles : sable, rochers, mares, dune, eau. Chacun a ses habitants."},{"id":"f57_ca_a_l_air_vide","label":"Une plage, c''est vide ?","consigne":"Posez la question, laissez venir « oui », puis lancez cinq minutes de recherche. Le décompte les contredit."}]'::jsonb WHERE id = '57';
UPDATE pedagogical_content SET actions = '[{"id":"f61_qui_est_passe","label":"Qui est passé par là","consigne":"Sur le sable humide, faites suivre une piste d''empreintes et deviner l''animal, sa taille, sa direction."},{"id":"f61_coquille_percee","label":"Le trou dans la coquille","consigne":"Cherchez une coquille percée d''un trou net. Faites deviner qui l''a fait et comment."}]'::jsonb WHERE id = '61';
UPDATE pedagogical_content SET actions = '[{"id":"f62_il_leve_la_tete","label":"Il a levé la tête","consigne":"Approchez lentement d''un oiseau et faites dire stop au premier changement : il cesse de manger, il vous fixe. C''est déjà trop près."},{"id":"f62_tant_qu_il_reste","label":"Tant qu''il ne s''envole pas ?","consigne":"Faites voter : y a-t-il dérangement si l''oiseau reste ? Oui, dès qu''il a arrêté de se nourrir."}]'::jsonb WHERE id = '62';
UPDATE pedagogical_content SET actions = '[{"id":"f63_deux_approches","label":"Deux façons d''approcher","consigne":"Un premier groupe avance normalement, le second en silence et à distance. Comparez ce que chacun a vu."},{"id":"f63_cinq_minutes_immobiles","label":"Cinq minutes sans bouger","consigne":"Tout le monde s''assoit et se tait cinq minutes. Comptez les animaux avant et après."}]'::jsonb WHERE id = '63';
UPDATE pedagogical_content SET actions = '[{"id":"f64_combien_d_envols","label":"Comptez les envols","consigne":"Faites compter les fois où un groupe d''oiseaux s''envole pendant votre présence. Chaque envol coûte un repas."},{"id":"f64_il_revient_pourtant","label":"Il revient, donc ça va ?","consigne":"Demandez si tout est réglé quand l''oiseau revient. L''énergie dépensée, elle, ne revient pas."}]'::jsonb WHERE id = '64';
UPDATE pedagogical_content SET actions = '[{"id":"f65_qui_est_la_en_ce_moment","label":"Qui est là en ce moment","consigne":"Faites chercher les indices de la saison : nids, jeunes, groupes en halte. Puis demandez ce qu''on verrait en janvier."},{"id":"f65_meme_endroit_autre_role","label":"Le même endroit, un autre rôle","consigne":"Faites lister à quoi sert cet endroit selon la saison : nurserie, halte, hivernage."}]'::jsonb WHERE id = '65';
UPDATE pedagogical_content SET actions = '[{"id":"f66_chez_qui_on_est","label":"On est chez qui ?","consigne":"Demandez à qui appartient cette plage. Puis faites lister ceux qui y vivent en permanence."},{"id":"f66_nos_traces","label":"Cherchez nos traces","consigne":"Avant de partir, faites chercher les marques de votre passage et les effacer. Bruit compris."}]'::jsonb WHERE id = '66';
UPDATE pedagogical_content SET actions = '[{"id":"f67_un_geste_chacun","label":"Un geste par personne","consigne":"Chacun nomme un geste qu''il peut tenir. On multiplie par le nombre de visiteurs de la plage cet été."},{"id":"f67_trop_petit","label":"C''est trop petit pour compter ?","consigne":"Laissez-les dire qu''un geste seul ne change rien. Puis faites le calcul à l''échelle de la saison."}]'::jsonb WHERE id = '67';
UPDATE pedagogical_content SET actions = '[{"id":"f96_pas_que_la_hauteur","label":"Pas que la hauteur","consigne":"Faites décrire la mer. Beaucoup ne parleront que de la taille des vagues. Relancez sur l''espacement et la direction."},{"id":"f96_bulletin_du_groupe","label":"Le bulletin du groupe","consigne":"Chargez deux stagiaires d''annoncer l''état de la mer au reste du groupe avant la mise à l''eau."}]'::jsonb WHERE id = '96';
UPDATE pedagogical_content SET actions = '[{"id":"f97_sans_mouiller_pieds","label":"Sans mouiller les pieds","consigne":"Depuis la plage, faites lister tout ce qu''on peut déjà savoir de la mer. La liste est plus longue qu''ils ne croient."},{"id":"f97_horizon_net","label":"L''horizon est net ?","consigne":"Faites juger la netteté de la ligne d''horizon. Floue, elle annonce souvent une dégradation en approche."}]'::jsonb WHERE id = '97';
UPDATE pedagogical_content SET actions = '[{"id":"f98_ca_nous_revient","label":"Ça finit où ?","consigne":"Prenez un polluant et faites suivre son trajet jusqu''à une assiette ou une baignade. La boucle se referme."},{"id":"f98_pourquoi_ce_panneau","label":"Pourquoi ce panneau","consigne":"Montrez un panneau de qualité des eaux et faites deviner qui il protège. Nous, autant que le milieu."}]'::jsonb WHERE id = '98';
UPDATE pedagogical_content SET actions = '[{"id":"f107_on_y_va_quand_meme","label":"C''était prévu, on y va ?","consigne":"Posez le cas d''une sortie programmée avec des conditions limites. Faites-les décider et justifier."},{"id":"f107_dans_une_heure","label":"Et dans une heure ?","consigne":"Faites prédire l''état de la mer en fin de séance à partir de ce qu''ils voient maintenant. On vérifie au retour."}]'::jsonb WHERE id = '107';
UPDATE pedagogical_content SET actions = '[{"id":"f111_combien_de_paysages","label":"Combien de paysages en dix kilomètres","consigne":"Faites lister les milieux traversés depuis chez eux jusqu''ici : mer, dune, plaine, bocage. La densité surprend."},{"id":"f111_richesse_ou_fragilite","label":"Riche ou fragile ?","consigne":"Demandez si cette variété est une force ou une faiblesse. Les deux — et c''est le sujet."}]'::jsonb WHERE id = '111';
UPDATE pedagogical_content SET actions = '[{"id":"f112_protege_donc_interdit","label":"Protégé veut dire interdit ?","consigne":"Faites voter. La plupart diront oui. Faites ensuite lister tout ce qui reste possible dans un site Natura 2000."},{"id":"f112_qui_decide","label":"Qui a décidé ça","consigne":"Demandez qui classe un site. Natura 2000 est un réseau européen, pas une décision locale."},{"id":"f112_quelle_part_de_mer","label":"Quelle part de la mer d''ici","consigne":"Faites parier quelle proportion des eaux normandes est classée. C''est un quart — beaucoup plus qu''ils ne pensent."}]'::jsonb WHERE id = '112';
UPDATE pedagogical_content SET actions = '[{"id":"f113_cap_ou_baie","label":"Cap ou baie ?","consigne":"Montrez un cap et une baie visibles. Faites parier où les vagues sont les plus fortes aujourd''hui."},{"id":"f113_trois_cents_metres","label":"Trois cents mètres plus loin","consigne":"Faites comparer la mer devant vous et celle d''un secteur voisin. Quelques centaines de mètres changent tout."}]'::jsonb WHERE id = '113';
